import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"
import modelProviders from "./docs/providers/index.json"

const sidebars: SidebarsConfig = {
	tutorialSidebar: [
		"index",
		{
			type: "category",
			label: "AI Code Orchestrator VSCode Extension",
			items: [
				"getting-started/installing",
				"getting-started/connecting-api-provider",
				"getting-started/your-first-task",
				"basic-usage/the-chat-interface",
				"basic-usage/typing-your-requests",
				"basic-usage/how-tools-work",
				"basic-usage/context-mentions",
				"basic-usage/using-modes",
				"tips-and-tricks",
				"reporting-errors",
				{
					label: "Features",
					type: "category",
					items: [
						"features/api-configuration-profiles",
						"features/auto-approving-actions",
						"features/boomerang-tasks",
						"features/checkpoints",
						"features/code-actions",
						"features/codebase-indexing",
						"features/custom-instructions",
						"features/diagnostics-integration",
						"features/custom-modes",
						"features/enhance-prompt",
						"features/settings-management",
						"features/intelligent-context-condensing",
						"features/keyboard-shortcuts",
						"features/marketplace",
						"features/message-queueing",
						"features/model-temperature",
						"features/concurrent-file-reads",
						"features/aicoignore",
						"features/skills",
						"features/slash-commands",
						"features/suggested-responses",
						"features/task-todo-list",
						"features/worktrees",
						"features/shell-integration",
						"features/more-features",
					],
				},
				{
					type: "category",
					label: "MCP",
					items: [
						{
							type: "doc",
							id: "features/mcp/overview",
							label: "MCP Overview",
						},
						"features/mcp/using-mcp-in-aico",
						"features/mcp/what-is-mcp",
						"features/mcp/server-transports",
						"features/mcp/mcp-vs-api",
						"features/mcp/recommended-mcp-servers",
					],
				},
				{
					type: "category",
					label: "Experimental",
					items: [
						"features/experimental/experimental-features",
						"features/experimental/custom-tools",
						"features/experimental/concurrent-file-edits",
						"features/experimental/background-editing",
						"features/image-generation",
						"advanced-usage/available-tools/run-slash-command",
					],
				},
				{
					type: "category",
					label: "Advanced Usage",
					items: [
						{
							type: "category",
							label: "Available Tools",
							items: [
								"advanced-usage/available-tools/tool-use-overview",
								"advanced-usage/available-tools/access-mcp-resource",
								"advanced-usage/available-tools/apply-diff",
								"advanced-usage/available-tools/apply-patch",
								"advanced-usage/available-tools/ask-followup-question",
								"advanced-usage/available-tools/attempt-completion",
								"advanced-usage/available-tools/codebase-search",
								"advanced-usage/available-tools/edit",
								"advanced-usage/available-tools/edit-file",
								"advanced-usage/available-tools/execute-command",
								"advanced-usage/available-tools/generate-image",
								"advanced-usage/available-tools/list-files",
								"advanced-usage/available-tools/new-task",
								"advanced-usage/available-tools/read-command-output",
								"advanced-usage/available-tools/read-file",
								"advanced-usage/available-tools/run-slash-command",
								"advanced-usage/available-tools/search-files",
								"advanced-usage/available-tools/search-replace",
								"advanced-usage/available-tools/skill",
								"advanced-usage/available-tools/switch-mode",
								"advanced-usage/available-tools/update-todo-list",
								"advanced-usage/available-tools/use-mcp-tool",
								"advanced-usage/available-tools/write-to-file",
							],
						},
						"advanced-usage/context-poisoning",
						"advanced-usage/large-projects",
						"advanced-usage/local-models",
						"advanced-usage/prompt-engineering",
						"advanced-usage/prompt-structure",
						"advanced-usage/rate-limits-costs",
						"advanced-usage/aico-code-nightly",
					],
				},
			],
		},
		{
			type: "category",
			label: "Model Providers",
			items: [
				{
					type: "doc",
					id: "providers/index",
					label: "About Model Providers",
				},
				...modelProviders.providers.map((provider) => ({
					type: "doc" as const,
					id: provider.id,
					label: provider.title,
				})),
			],
		},
		{
			type: "category",
			label: "Extension Release Notes",
			items: [
				"update-notes/index",
				{
					type: "category",
					label: "1.3",
					items: [
						{ type: "doc", id: "update-notes/v1.3.2", label: "1.3.2" },
						{ type: "doc", id: "update-notes/v1.3.1", label: "1.3.1" },
						{ type: "doc", id: "update-notes/v1.3.0", label: "1.3.0" },
					],
				},
				{
					type: "category",
					label: "1.2",
					items: [
						{ type: "doc", id: "update-notes/v1.2.2", label: "1.2.2" },
						{ type: "doc", id: "update-notes/v1.2.1", label: "1.2.1" },
						{ type: "doc", id: "update-notes/v1.2.0", label: "1.2.0" },
					],
				},
				{
					type: "category",
					label: "1.1",
					items: [
						{ type: "doc", id: "update-notes/v1.1.4", label: "1.1.4" },
						{ type: "doc", id: "update-notes/v1.1.2", label: "1.1.2" },
						{ type: "doc", id: "update-notes/v1.1.1", label: "1.1.1" },
						{ type: "doc", id: "update-notes/v1.1.0", label: "1.1.0" },
					],
				},
				{
					type: "category",
					label: "1.0",
					items: [{ type: "doc", id: "update-notes/v1.0.0", label: "1.0.0" }],
				},
			],
		},
		{
			type: "doc",
			label: "FAQ",
			id: "faq",
		},
		{
			type: "link",
			label: "Roocabulary (GitHub)",
			href: "https://github.com/cannuri/Roocabulary",
		},
	],
}

export default sidebars
