blank_issues_enabled: false
contact_links:
    - name: Leave a Review
      url: https://marketplace.visualstudio.com/items?itemName=mihas2.ai-code-orchestrator&ssr=false#review-details
      about: Enjoying AI Code Orchestrator? Leave a review here!
